export enum ESocketIncomingMessage {
    JOIN_CALL = "JOIN_CALL",
    GET_ROUTER_RTP_CAPABILITIES = "GET_ROUTER_RTP_CAPABILITIES",
    CREATE_PRODUCER_TRANSPORT = "CREATE_PRODUCER_TRANSPORT",
    CREATE_CONSUMER_TRANSPORT = "CREATE_CONSUMER_TRANSPORT",
    CONNECT_TRANSPORT = "CONNECT_TRANSPORT",
    PRODUCE = "PRODUCE",
    CONSUME = "CONSUME",
}

export enum ESocketOutgoingMessage {
    ROUTER_RTP_CAPABILITIES = "ROUTER_RTP_CAPABILITIES",
    PRODUCER_TRANSPORT_CREATED = "PRODUCER_TRANSPORT_CREATED",
    CONSUMER_TRANSPORT_CREATED = "CONSUMER_TRANSPORT_CREATED",
    TRANSPORT_CONNECTED = "PRODUCER_TRANSPORT_CONNECTED",
    PRODUCER_CREATED = "PRODUCER_CREATED",
    CONSUMER_CREATED = "CONSUMER_CREATED",
}