export enum ESocketIncomingMessage {
    JOIN_CALL = "JOIN_CALL",
    GET_ROUTER_RTP_CAPABILITIES = "GET_ROUTER_RTP_CAPABILITIES",
    CREATE_TRANSPORT = "CREATE_TRANSPORT",
    CONNECT_TRANSPORT = "CONNECT_TRANSPORT",
    PRODUCE = "PRODUCE",
    CONSUME = "CONSUME",
    RECV_CONNECT = "RECV_CONNECT",
    CONSUMER_RESUME = "CONSUMER_RESUME"
}

export enum ESocketOutgoingMessage {
    ROUTER_RTP_CAPABILITIES = "ROUTER_RTP_CAPABILITIES",
    TRANSPORT_CREATED = "TRANSPORT_CREATED",
    TRANSPORT_CONNECTED = "PRODUCER_TRANSPORT_CONNECTED",
    PRODUCER_CREATED = "PRODUCER_CREATED",
    CONSUMER_CREATED = "CONSUMER_CREATED",
}