export enum EMediaTypes {
  AUDIO_TYPE = "AUDIO_TYPE",
  VIDEO_TYPE = "VIDEO_TYPE",
  SCREEN_TYPE = "SCREEN_TYPE",
}

export enum EEventTypes {
  EXIT_ROOM = "EXIT_ROOM",
  OPEN_ROOM = "OPEN_ROOM",
  START_VIDEO = "START_VIDEO",
  STOP_VIDEO = "STOP_VIDEO",
  START_AUDIO = "START_AUDIO",
  STOP_AUDIO = "STOP_AUDIO",
  START_SCREEN = "START_SCREEN",
  STOP_SCREEN = "STOP_SCREEN",
}
